export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO="DELETE_TODO"
export const UPDATE_TODO="UPDATE_TODO"
export const FILTER_TODO="FILTER_TODO";
export const TOGGLE_ALL="TOGGLE_ALL";
export const UN_TOGGLE_ALL="UN_TOGGLE_ALL";
export const GET_ALL_TODO="GET_ALL_TODO";
export const TOGGLE_TODO="TOGGLE_TODO";
export const UN_TOGGLE_TODO="UN_TOGGLE_TODO";